# Generated by Django 4.2.4 on 2024-03-16 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_amount", models.FloatField()),
                ("total_over_loan_term", models.FloatField()),
                ("monthly_payment", models.FloatField()),
                ("interest_rate", models.FloatField()),
                ("mortgage_term", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
